spring.application.name=alquimia-literaria

spring.config.import=optional:file:.env[.properties]

# PostgreSQL Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cambia el nivel global a solo Advertencias y Errores
logging.level.root=WARN

# ==========================================
# Configuración de OpenAPI / Swagger UI
# ==========================================
springdoc.swagger-ui.path=/swagger-ui.html
# Tu ruta del motor de OpenAPI es /v3/api-docs
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

# ==========================================
# Configuración de Scalar
# ==========================================
scalar.enabled=true
scalar.path=/docs
scalar.theme=deepSpace

# Aquí tenés la URL exacta apuntando a tu servidor de Render con la ruta /v3/api-docs
scalar.url=https://biblioteca-digital-grupo-6.onrender.com/v3/api-docs